### ISSUE TITLE
failed to create containers kindccm on applying LoadBalancer example with kubectl 

### ISSUE THREAD

**Issue by LogExE** [kubernetes-sigs/cloud-provider-kind#116] opened 2024-08-18 12:34 UTC
I get error when trying to run an example from https://kind.sigs.k8s.io/docs/user/loadbalancer/
I use podman driver. My system is Fedora Silverblue 40.

Steps to reproduce:
1. Be on latest Fedora Silverblue version
2. Run `sudo kind create cluster`
3. Run `sudo cloud-provider-kind`
4. Execute `sudo kubectl apply` for manifest https://kind.sigs.k8s.io/examples/loadbalancer/usage.yaml
5. Now cloud-provider-kind constantly prints error on failing to create container

The error:
```sh
E0818 16:24:32.239123   25489 controller.go:298] error processing service default/foo-service (retrying with exponential backoff): failed to ensure load balancer: failed to create continers kindccm-TLRDKPBWWH4DUSI7J7BNE3ABETEPCKSYA6UIWR5B [--detach --tty --label io.x-k8s.cloud-provider-kind.cluster=kind --label io.x-k8s.cloud-provider-kind.loadbalancer.name=kind/default/foo-service --net kind --init=false --hostname kindccm-TLRDKPBWWH4DUSI7J7BNE3ABETEPCKSYA6UIWR5B --privileged --restart=on-failure --sysctl=net.ipv4.ip_forward=1 --sysctl=net.ipv6.conf.all.disable_ipv6=0 --sysctl=net.ipv6.conf.all.forwarding=1 --sysctl=net.ipv4.conf.all.rp_filter=0 --publish=10000/TCP --publish-all envoyproxy/envoy:v1.30.1 bash -c echo -en 'node:
  cluster: cloud-provider-kind
  id: cloud-provider-kind-id

dynamic_resources:
  cds_config:
    resource_api_version: V3
    path: /home/envoy/cds.yaml
  lds_config:
    resource_api_version: V3
    path: /home/envoy/lds.yaml

admin:
  access_log_path: /dev/stdout
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 10000
' > /home/envoy/envoy.yaml && touch /home/envoy/cds.yaml && touch /home/envoy/lds.yaml && while true; do envoy -c /home/envoy/envoy.yaml && break; sleep 1; done]: exit status 125
```

**Comment by aojea** [comment] 2024-08-19 12:46
Interesting ... can you list what containers are actually running ?
I think it is something as `podman ps -a` and the networks `podman network ls`?

any reason to run anything with sudo?

**Comment by vially** [comment] 2024-08-19 22:11
I had a similar issue and in _my case_ it was caused by `cloud-provider-kind` [using an unqualified image name](https://github.com/kubernetes-sigs/cloud-provider-kind/blob/827fdb16eda5d85eb055a7cad9ed2c1a14a415ae/pkg/loadbalancer/proxy.go#L24) for the `envoyproxy/envoy` image and podman on my system not having `docker.io` configured as part of the `unqualified-search-registries` array.

As a workaround I've added an image shortname alias for it to `/etc/containers/registries.conf.d/00-shortnames.conf`:
```toml
[aliases]
# ...
"envoyproxy/envoy" = "docker.io/envoyproxy/envoy"
```

**Comment by aojea** [comment] 2024-08-19 23:30
> I had a similar issue and in _my case_ it was caused by `cloud-provider-kind` [using an unqualified image name](https://github.com/kubernetes-sigs/cloud-provider-kind/blob/827fdb16eda5d85eb055a7cad9ed2c1a14a415ae/pkg/loadbalancer/proxy.go#L24) for the `envoyproxy/envoy` image and podman on my system not having `docker.io` configured as part of the `unqualified-search-registries` array.
> 
> As a workaround I've added an image shortname alias for it to `/etc/containers/registries.conf.d/00-shortnames.conf`:
> 
> ```toml
> [aliases]
> # ...
> "envoyproxy/envoy" = "docker.io/envoyproxy/envoy"
> ```

oh, @vially (or someone interested) do you mind to send a PR to update the existing image with the fully qualified name

https://github.com/kubernetes-sigs/cloud-provider-kind/blob/827fdb16eda5d85eb055a7cad9ed2c1a14a415ae/pkg/loadbalancer/proxy.go#L24

**Comment by BenTheElder** [comment] 2024-08-20 18:35
> I had a similar issue and in my case it was caused by cloud-provider-kind [using an unqualified image name](https://github.com/kubernetes-sigs/cloud-provider-kind/blob/827fdb16eda5d85eb055a7cad9ed2c1a14a415ae/pkg/loadbalancer/proxy.go#L24) for the envoyproxy/envoy image and podman on my system not having docker.io configured as part of the unqualified-search-registries array.

In `kind` we wound up having the internal podman shim rewrite unqualified images to docker.io/, because kubernetes also does this internally and the consistency is helpful for our use case.

**Comment by BenTheElder** [comment] 2024-08-20 18:37
https://github.com/kubernetes-sigs/kind/blob/b12e445afb936730f614ff067aae06c7ba3b2c42/pkg/cluster/internal/providers/podman/images.go#L86

This is probably not worth the complexity for a single currently non-configurable image though.

We can copy code between the repos if needed and keep it internal (it's not a great API at the moment), because they're under the same license and license header under the same overall project.

**Comment by LogExE** [comment] 2024-08-29 19:30
Sorry for absence. I confirm that error goes away after making alias in shortnames.conf

**Comment by aojea** [comment] 2024-08-29 22:40
> Sorry for absence. I confirm that error goes away after making alias in shortnames.conf

no worries, so I think we can close as this will be fixed by https://github.com/kubernetes-sigs/cloud-provider-kind/pull/124

**Closed by aojea** 2024-08-29 22:40 UTC
